# Generated by Django 5.2.5 on 2025-08-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
