# Generated by Django 5.2.5 on 2025-08-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVuelos', '0002_alter_vuelo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
